<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $employees = [
            [
                'ControlNo'      => '018308',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'PUBLIC SAFETY AND SECURITY MANAGEMENT GROUP',
                'division'       => null,
                'section'        => null,
                'unit'           => null,
                'position'       => 'EXECUTIVE ASSISTANT IV',
                'tblStructureID' => 4,
                'sg'             => 22,
                'level'          => 'S',
                'positionID'     => 259,
                'itemNo'         => 78,
                'pageNo'         => 6,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'MICHAEL M. TULEN',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '020385',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'BUSINESS AND TAX MANAGEMENT GROUP',
                'division'       => null,
                'section'        => null,
                'unit'           => null,
                'position'       => 'EXECUTIVE ASSISTANT III',
                'tblStructureID' => 4,
                'sg'             => 20,
                'level'          => 'S',
                'positionID'     => 249,
                'itemNo'         => 16,
                'pageNo'         => 2,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'ARTHUR S. ANSALE',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '020679',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'BUSINESS AND TAX MANAGEMENT GROUP',
                'division'       => null,
                'section'        => null,
                'unit'           => null,
                'position'       => 'EXECUTIVE ASSISTANT III',
                'tblStructureID' => 4,
                'sg'             => 20,
                'level'          => 'S',
                'positionID'     => 249,
                'itemNo'         => 17,
                'pageNo'         => 2,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'RICKY F. TIJON',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '022194',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'BUSINESS AND TAX MANAGEMENT GROUP',
                'division'       => null,
                'section'        => null,
                'unit'           => null,
                'position'       => 'EXECUTIVE ASSISTANT II',
                'tblStructureID' => 4,
                'sg'             => 17,
                'level'          => 'S',
                'positionID'     => 910,
                'itemNo'         => 19,
                'pageNo'         => 2,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'MICO JOHN D. DELA CALZADA',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '018559',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'BUSINESS AND TAX MANAGEMENT GROUP',
                'division'       => null,
                'section'        => null,
                'unit'           => null,
                'position'       => 'EXECUTIVE ASSISTANT II',
                'tblStructureID' => 4,
                'sg'             => 17,
                'level'          => 'S',
                'positionID'     => 910,
                'itemNo'         => 18,
                'pageNo'         => 2,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'MARIO F. RAPAS',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '001747',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'BUSINESS AND TAX MANAGEMENT GROUP',
                'division'       => null,
                'section'        => null,
                'unit'           => null,
                'position'       => 'EXECUTIVE ASSISTANT IV',
                'tblStructureID' => 4,
                'sg'             => 22,
                'level'          => 'S',
                'positionID'     => 259,
                'itemNo'         => 15,
                'pageNo'         => 2,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'EVELYN B. CHUA',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '001655',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'INFORMATION AND EDUCATION DEVELOPMENT GROUP',
                'division'       => null,
                'section'        => null,
                'unit'           => null,
                'position'       => 'EXECUTIVE ASSISTANT IV',
                'tblStructureID' => 4,
                'sg'             => 22,
                'level'          => 'S',
                'positionID'     => 259,
                'itemNo'         => 46,
                'pageNo'         => 4,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'TEOTIMA A. EDIG',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '018562',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'INFORMATION AND EDUCATION DEVELOPMENT GROUP',
                'division'       => null,
                'section'        => null,
                'unit'           => null,
                'position'       => 'EXECUTIVE ASSISTANT II',
                'tblStructureID' => 4,
                'sg'             => 17,
                'level'          => 'S',
                'positionID'     => 910,
                'itemNo'         => 49,
                'pageNo'         => 4,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'AGAPITO ALLAN J. HIOCA',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '018401',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'INFORMATION AND EDUCATION DEVELOPMENT GROUP',
                'division'       => null,
                'section'        => null,
                'unit'           => null,
                'position'       => 'EXECUTIVE ASSISTANT II',
                'tblStructureID' => 4,
                'sg'             => 17,
                'level'          => 'S',
                'positionID'     => 910,
                'itemNo'         => 50,
                'pageNo'         => 4,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'OCTAVIO R. VALLE',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '019133',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'INFORMATION AND EDUCATION DEVELOPMENT GROUP',
                'division'       => null,
                'section'        => null,
                'unit'           => null,
                'position'       => 'EXECUTIVE ASSISTANT III',
                'tblStructureID' => 4,
                'sg'             => 20,
                'level'          => 'S',
                'positionID'     => 249,
                'itemNo'         => 47,
                'pageNo'         => 4,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'JANICE B. CLARION',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '019402',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'INFORMATION AND EDUCATION DEVELOPMENT GROUP',
                'division'       => null,
                'section'        => null,
                'unit'           => null,
                'position'       => 'EXECUTIVE ASSISTANT III',
                'tblStructureID' => 4,
                'sg'             => 20,
                'level'          => 'S',
                'positionID'     => 249,
                'itemNo'         => 48,
                'pageNo'         => 4,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'KEANO JAY A. PONO',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // Civil Security Section
            [
                'ControlNo'      => '018325',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'PUBLIC SAFETY AND SECURITY MANAGEMENT GROUP',
                'division'       => null,
                'section'        => 'CIVIL SECURITY SECTION',
                'unit'           => null,
                'position'       => 'SECURITY AGENT II',
                'tblStructureID' => 4,
                'sg'             => 10,
                'level'          => 'S',
                'positionID'     => 125,
                'itemNo'         => 98,
                'pageNo'         => 7,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'ROMEO M. OBERO',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '018327',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'PUBLIC SAFETY AND SECURITY MANAGEMENT GROUP',
                'division'       => null,
                'section'        => 'CIVIL SECURITY SECTION',
                'unit'           => null,
                'position'       => 'SECURITY AGENT II',
                'tblStructureID' => 4,
                'sg'             => 10,
                'level'          => 'S',
                'positionID'     => 125,
                'itemNo'         => 101,
                'pageNo'         => 7,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'FELIXBERTO G. MAGALLON',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '016419',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'PUBLIC SAFETY AND SECURITY MANAGEMENT GROUP',
                'division'       => null,
                'section'        => 'CIVIL SECURITY SECTION',
                'unit'           => null,
                'position'       => 'SECURITY AGENT II',
                'tblStructureID' => 4,
                'sg'             => 10,
                'level'          => 'S',
                'positionID'     => 125,
                'itemNo'         => 100,
                'pageNo'         => 7,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'MARY JOY B. GABONADA',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '018755',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'PUBLIC SAFETY AND SECURITY MANAGEMENT GROUP',
                'division'       => null,
                'section'        => 'CIVIL SECURITY SECTION',
                'unit'           => null,
                'position'       => 'SECURITY OFFICER II',
                'tblStructureID' => 4,
                'sg'             => 15,
                'level'          => 'S',
                'positionID'     => 9404,
                'itemNo'         => 86,
                'pageNo'         => 6,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'ERIC J. BALOYO',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '021507',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'PUBLIC SAFETY AND SECURITY MANAGEMENT GROUP',
                'division'       => null,
                'section'        => 'CIVIL SECURITY SECTION',
                'unit'           => null,
                'position'       => 'SECURITY AGENT II',
                'tblStructureID' => 4,
                'sg'             => 10,
                'level'          => 'S',
                'positionID'     => 125,
                'itemNo'         => 99,
                'pageNo'         => 7,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'DIOMEDES B. MIANO',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '021546',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'PUBLIC SAFETY AND SECURITY MANAGEMENT GROUP',
                'division'       => null,
                'section'        => 'CIVIL SECURITY SECTION',
                'unit'           => null,
                'position'       => 'SECURITY OFFICER III',
                'tblStructureID' => 4,
                'sg'             => 18,
                'level'          => 'S',
                'positionID'     => 230,
                'itemNo'         => 85,
                'pageNo'         => 6,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'FRANCISCO H. LEE',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '002744',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'PUBLIC SAFETY AND SECURITY MANAGEMENT GROUP',
                'division'       => null,
                'section'        => 'CIVIL SECURITY SECTION',
                'unit'           => null,
                'position'       => 'SECURITY AGENT II',
                'tblStructureID' => 4,
                'sg'             => 10,
                'level'          => 'S',
                'positionID'     => 125,
                'itemNo'         => 102,
                'pageNo'         => 7,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'GERARDO G. DEL ROSARIO',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // Special Program Management Group 1
            [
                'ControlNo'      => '018307',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'SPECIAL PROGRAM MANAGEMENT GROUP 1',
                'division'       => null,
                'section'        => null,
                'unit'           => null,
                'position'       => 'EXECUTIVE ASSISTANT III',
                'tblStructureID' => 4,
                'sg'             => 20,
                'level'          => 'S',
                'positionID'     => 249,
                'itemNo'         => 125,
                'pageNo'         => 9,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'ROGELIO A. TOROCTOCON',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '009974',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'SPECIAL PROGRAM MANAGEMENT GROUP 1',
                'division'       => null,
                'section'        => null,
                'unit'           => null,
                'position'       => 'EXECUTIVE ASSISTANT IV',
                'tblStructureID' => 4,
                'sg'             => 22,
                'level'          => 'S',
                'positionID'     => 259,
                'itemNo'         => 123,
                'pageNo'         => 8,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'SAMUEL U. ANGOY',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '018283',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'SPECIAL PROGRAM MANAGEMENT GROUP 1',
                'division'       => null,
                'section'        => null,
                'unit'           => null,
                'position'       => 'EXECUTIVE ASSISTANT III',
                'tblStructureID' => 4,
                'sg'             => 20,
                'level'          => 'S',
                'positionID'     => 249,
                'itemNo'         => 124,
                'pageNo'         => 8,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'DANTE P. CARIAGA',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '008033',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'SPECIAL PROGRAM MANAGEMENT GROUP 1',
                'division'       => null,
                'section'        => null,
                'unit'           => null,
                'position'       => 'EXECUTIVE ASSISTANT I',
                'tblStructureID' => 4,
                'sg'             => 14,
                'level'          => 'S',
                'positionID'     => 11502,
                'itemNo'         => 128,
                'pageNo'         => 9,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'RONILO A. DACLISON',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // Special Program Management Group 2
            [
                'ControlNo'      => '007210',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'SPECIAL PROGRAM MANAGEMENT GROUP 2',
                'division'       => null,
                'section'        => null,
                'unit'           => null,
                'position'       => 'EXECUTIVE ASSISTANT IV',
                'tblStructureID' => 4,
                'sg'             => 22,
                'level'          => 'S',
                'positionID'     => 259,
                'itemNo'         => 150,
                'pageNo'         => 10,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'MARJESSA FLOR V. DUBLIN',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '009890',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'SPECIAL PROGRAM MANAGEMENT GROUP 2',
                'division'       => null,
                'section'        => null,
                'unit'           => null,
                'position'       => 'EXECUTIVE ASSISTANT III',
                'tblStructureID' => 4,
                'sg'             => 20,
                'level'          => 'S',
                'positionID'     => 249,
                'itemNo'         => 151,
                'pageNo'         => 10,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'MARCELO V. LONGAKIT',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '000176',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'SPECIAL PROGRAM MANAGEMENT GROUP 2',
                'division'       => null,
                'section'        => null,
                'unit'           => null,
                'position'       => 'EXECUTIVE ASSISTANT II',
                'tblStructureID' => 4,
                'sg'             => 17,
                'level'          => 'S',
                'positionID'     => 910,
                'itemNo'         => 154,
                'pageNo'         => 10,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'REX B. RAMOS',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '001408',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'SPECIAL PROGRAM MANAGEMENT GROUP 2',
                'division'       => null,
                'section'        => null,
                'unit'           => null,
                'position'       => 'EXECUTIVE ASSISTANT II',
                'tblStructureID' => 4,
                'sg'             => 17,
                'level'          => 'S',
                'positionID'     => 910,
                'itemNo'         => 153,
                'pageNo'         => 10,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'CESAR JR. IV J. PETALLANA',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '018306',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'SPECIAL PROGRAM MANAGEMENT GROUP 2',
                'division'       => null,
                'section'        => null,
                'unit'           => null,
                'position'       => 'EXECUTIVE ASSISTANT III',
                'tblStructureID' => 4,
                'sg'             => 20,
                'level'          => 'S',
                'positionID'     => 249,
                'itemNo'         => 152,
                'pageNo'         => 10,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'ERNESTO M. TAGALINAO',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // Business and Tax - Tagum City Business and Incentive Division
            [
                'ControlNo'      => '003888',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'BUSINESS AND TAX MANAGEMENT GROUP',
                'division'       => 'TAGUM CITY BUSINESS AND INCENTIVE DIVISION',
                'section'        => null,
                'unit'           => null,
                'position'       => 'PROJECT DEVELOPMENT OFFICER III',
                'tblStructureID' => 4,
                'sg'             => 18,
                'level'          => 'S',
                'positionID'     => 225,
                'itemNo'         => 21,
                'pageNo'         => 2,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'HAROLD JOHN J. JUMAWID',
                'status'         => 'REGULAR',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // Business Permit and Licensing Division
            [
                'ControlNo'      => '001564',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'BUSINESS AND TAX MANAGEMENT GROUP',
                'division'       => 'BUSINESS PERMIT AND LICENSING DIVISION',
                'section'        => null,
                'unit'           => null,
                'position'       => 'LICENSING OFFICER IV',
                'tblStructureID' => 4,
                'sg'             => 22,
                'level'          => 'S',
                'positionID'     => 263,
                'itemNo'         => 26,
                'pageNo'         => 2,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'IAN KEVIN E. VALLE',
                'status'         => 'REGULAR',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '003358',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'BUSINESS AND TAX MANAGEMENT GROUP',
                'division'       => 'BUSINESS PERMIT AND LICENSING DIVISION',
                'section'        => 'ADMINISTRATIVE SECTION',
                'unit'           => null,
                'position'       => 'ADMINISTRATIVE OFFICER V',
                'tblStructureID' => 4,
                'sg'             => 18,
                'level'          => 'A',
                'positionID'     => 14691,
                'itemNo'         => 27,
                'pageNo'         => 3,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'MARITES L. CASAS',
                'status'         => 'REGULAR',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '005267',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'BUSINESS AND TAX MANAGEMENT GROUP',
                'division'       => 'BUSINESS PERMIT AND LICENSING DIVISION',
                'section'        => 'LICENSING AND FRANCHISING SECTION',
                'unit'           => null,
                'position'       => 'LICENSING OFFICER I',
                'tblStructureID' => 4,
                'sg'             => 11,
                'level'          => 'S',
                'positionID'     => 140,
                'itemNo'         => 32,
                'pageNo'         => 3,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'ALLAN REY R. PAGDILAO',
                'status'         => 'REGULAR',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '005521',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'BUSINESS AND TAX MANAGEMENT GROUP',
                'division'       => 'BUSINESS PERMIT AND LICENSING DIVISION',
                'section'        => 'LICENSING AND FRANCHISING SECTION',
                'unit'           => null,
                'position'       => 'ADMINISTRATIVE ASSISTANT III (COMPUTER OPERATOR II)',
                'tblStructureID' => 4,
                'sg'             => 9,
                'level'          => 'A',
                'positionID'     => 1184,
                'itemNo'         => 35,
                'pageNo'         => 3,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'EDEN M. FACINAL',
                'status'         => 'REGULAR',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '000062',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'BUSINESS AND TAX MANAGEMENT GROUP',
                'division'       => 'BUSINESS PERMIT AND LICENSING DIVISION',
                'section'        => 'LICENSING AND FRANCHISING SECTION',
                'unit'           => null,
                'position'       => 'LICENSING OFFICER III',
                'tblStructureID' => 4,
                'sg'             => 18,
                'level'          => 'S',
                'positionID'     => 217,
                'itemNo'         => 30,
                'pageNo'         => 3,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'ELJAEN A. DUMANDAN',
                'status'         => 'REGULAR',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '000091',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'BUSINESS AND TAX MANAGEMENT GROUP',
                'division'       => 'BUSINESS PERMIT AND LICENSING DIVISION',
                'section'        => 'LICENSING AND FRANCHISING SECTION',
                'unit'           => null,
                'position'       => 'ADMINISTRATIVE ASSISTANT III (COMPUTER OPERATOR II)',
                'tblStructureID' => 4,
                'sg'             => 9,
                'level'          => 'A',
                'positionID'     => 1184,
                'itemNo'         => 34,
                'pageNo'         => 3,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'JOY B. ERFE',
                'status'         => 'REGULAR',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '001090',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'BUSINESS AND TAX MANAGEMENT GROUP',
                'division'       => 'BUSINESS PERMIT AND LICENSING DIVISION',
                'section'        => 'INSPECTION AND TAX MAPPING SECTION',
                'unit'           => null,
                'position'       => 'LICENSING OFFICER III',
                'tblStructureID' => 4,
                'sg'             => 18,
                'level'          => 'S',
                'positionID'     => 217,
                'itemNo'         => 36,
                'pageNo'         => 3,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'ANNA JEAN B. MONTOYA',
                'status'         => 'REGULAR',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '005876',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'BUSINESS AND TAX MANAGEMENT GROUP',
                'division'       => 'BUSINESS PERMIT AND LICENSING DIVISION',
                'section'        => 'INSPECTION AND TAX MAPPING SECTION',
                'unit'           => null,
                'position'       => 'LICENSE INSPECTOR II',
                'tblStructureID' => 4,
                'sg'             => 8,
                'level'          => 'S',
                'positionID'     => 83,
                'itemNo'         => 40,
                'pageNo'         => 3,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'JENNIFER A. CERONA',
                'status'         => 'REGULAR',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '010031',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'BUSINESS AND TAX MANAGEMENT GROUP',
                'division'       => 'BUSINESS PERMIT AND LICENSING DIVISION',
                'section'        => 'INSPECTION AND TAX MAPPING SECTION',
                'unit'           => null,
                'position'       => 'TAX MAPPING AIDE',
                'tblStructureID' => 4,
                'sg'             => 4,
                'level'          => 'S',
                'positionID'     => 52,
                'itemNo'         => 42,
                'pageNo'         => 3,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'HONEY JEAN L. ROBLE',
                'status'         => 'REGULAR',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '011900',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'BUSINESS AND TAX MANAGEMENT GROUP',
                'division'       => 'BUSINESS PERMIT AND LICENSING DIVISION',
                'section'        => 'INSPECTION AND TAX MAPPING SECTION',
                'unit'           => null,
                'position'       => 'TAX MAPPER I',
                'tblStructureID' => 4,
                'sg'             => 11,
                'level'          => 'S',
                'positionID'     => 158,
                'itemNo'         => 38,
                'pageNo'         => 3,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'HAZEL MAE B. ISIDORO',
                'status'         => 'REGULAR',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '003290',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'BUSINESS AND TAX MANAGEMENT GROUP',
                'division'       => 'BUSINESS PERMIT AND LICENSING DIVISION',
                'section'        => 'INSPECTION AND TAX MAPPING SECTION',
                'unit'           => null,
                'position'       => 'LICENSE INSPECTOR II',
                'tblStructureID' => 4,
                'sg'             => 8,
                'level'          => 'S',
                'positionID'     => 83,
                'itemNo'         => 41,
                'pageNo'         => 3,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'FRANCISE JUVY D. ALEGADO',
                'status'         => 'REGULAR',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '016884',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'BUSINESS AND TAX MANAGEMENT GROUP',
                'division'       => 'BUSINESS PERMIT AND LICENSING DIVISION',
                'section'        => 'INSPECTION AND TAX MAPPING SECTION',
                'unit'           => null,
                'position'       => 'TAX MAPPER I',
                'tblStructureID' => 4,
                'sg'             => 11,
                'level'          => 'S',
                'positionID'     => 158,
                'itemNo'         => 39,
                'pageNo'         => 3,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'SITTIE HAKIMA T. ABDUL HALIM',
                'status'         => 'REGULAR',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '000103',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'BUSINESS AND TAX MANAGEMENT GROUP',
                'division'       => 'BUSINESS PERMIT AND LICENSING DIVISION',
                'section'        => 'RECORDS MANAGEMENT SECTION',
                'unit'           => null,
                'position'       => 'ADMINISTRATIVE OFFICER III (RECORDS OFFICER II)',
                'tblStructureID' => 4,
                'sg'             => 14,
                'level'          => 'A',
                'positionID'     => 1156,
                'itemNo'         => 44,
                'pageNo'         => 4,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'MILA O. MACATUPO',
                'status'         => 'REGULAR',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // City Information Division
            [
                'ControlNo'      => '012072',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'INFORMATION AND EDUCATION DEVELOPMENT GROUP',
                'division'       => 'CITY INFORMATION DIVISION',
                'section'        => 'MULTIMEDIA SECTION',
                'unit'           => 'SOCIAL MEDIA UNIT',
                'position'       => 'ADMINISTRATIVE ASSISTANT I (PHOTOGRAPHER II)',
                'tblStructureID' => 4,
                'sg'             => 7,
                'level'          => 'A',
                'positionID'     => 79,
                'itemNo'         => 58,
                'pageNo'         => 5,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'VINZEL BRET DAVO',
                'status'         => 'REGULAR',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '008231',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'INFORMATION AND EDUCATION DEVELOPMENT GROUP',
                'division'       => 'CITY INFORMATION DIVISION',
                'section'        => 'MULTIMEDIA SECTION',
                'unit'           => null,
                'position'       => 'ADMINISTRATIVE OFFICER V (INFORMATION OFFICER III)',
                'tblStructureID' => 4,
                'sg'             => 18,
                'level'          => 'A',
                'positionID'     => 1179,
                'itemNo'         => 55,
                'pageNo'         => 4,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'LEUNIELON A. TIMOGAN',
                'status'         => 'REGULAR',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // City Education Development Division
            [
                'ControlNo'      => '001567',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'INFORMATION AND EDUCATION DEVELOPMENT GROUP',
                'division'       => 'CITY EDUCATION DEVELOPMENT DIVISION',
                'section'        => null,
                'unit'           => null,
                'position'       => 'LIBRARIAN III',
                'tblStructureID' => 4,
                'sg'             => 18,
                'level'          => 'S',
                'positionID'     => 216,
                'itemNo'         => 69,
                'pageNo'         => 5,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'ENRIQUE H. DONAYRE',
                'status'         => 'REGULAR',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '010062',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'INFORMATION AND EDUCATION DEVELOPMENT GROUP',
                'division'       => 'CITY EDUCATION DEVELOPMENT DIVISION',
                'section'        => null,
                'unit'           => null,
                'position'       => 'ADMINISTRATIVE ASSISTANT I (AUDIO-VISUAL EQUIPMENT OPERATOR III)',
                'tblStructureID' => 4,
                'sg'             => 7,
                'level'          => 'A',
                'positionID'     => 11476,
                'itemNo'         => 76,
                'pageNo'         => 6,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'GLEIZA B. DELGADO',
                'status'         => 'REGULAR',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // Youth Development Division
            [
                'ControlNo'      => '007898',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'SPECIAL PROGRAM MANAGEMENT GROUP 1',
                'division'       => 'YOUTH DEVELOPMENT DIVISION',
                'section'        => null,
                'unit'           => 'PROJECT MANAGEMENT AND POLICY DEVELOPMENT UNIT',
                'position'       => 'PROJECT DEVELOPMENT ASSISTANT',
                'tblStructureID' => 4,
                'sg'             => 8,
                'level'          => 'S',
                'positionID'     => 84,
                'itemNo'         => 134,
                'pageNo'         => 9,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'JACQUELINE GRACE Q. EDULLANTES',
                'status'         => 'REGULAR',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '018316',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'SPECIAL PROGRAM MANAGEMENT GROUP 1',
                'division'       => 'YOUTH DEVELOPMENT DIVISION',
                'section'        => null,
                'unit'           => 'PROJECT MANAGEMENT AND POLICY DEVELOPMENT UNIT',
                'position'       => 'YOUTH DEVELOPMENT OFFICER II',
                'tblStructureID' => 4,
                'sg'             => 14,
                'level'          => 'S',
                'positionID'     => 179,
                'itemNo'         => 132,
                'pageNo'         => 9,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'LOVELY D. FUERZAS',
                'status'         => 'REGULAR',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // Administrative and Fiscal Management Group
            [
                'ControlNo'      => '018556',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'ADMINISTRATIVE AND FISCAL MANAGEMENT GROUP',
                'division'       => null,
                'section'        => null,
                'unit'           => null,
                'position'       => 'EXECUTIVE ASSISTANT III',
                'tblStructureID' => 4,
                'sg'             => 20,
                'level'          => 'S',
                'positionID'     => 249,
                'itemNo'         => 3,
                'pageNo'         => 1,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'FLORENCIO CARLO S. DOMINGO',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '005291',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'ADMINISTRATIVE AND FISCAL MANAGEMENT GROUP',
                'division'       => null,
                'section'        => null,
                'unit'           => null,
                'position'       => 'EXECUTIVE ASSISTANT III',
                'tblStructureID' => 4,
                'sg'             => 20,
                'level'          => 'S',
                'positionID'     => 249,
                'itemNo'         => 4,
                'pageNo'         => 1,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'ROMELYN Q. FORTUNA',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '006430',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'ADMINISTRATIVE AND FISCAL MANAGEMENT GROUP',
                'division'       => null,
                'section'        => null,
                'unit'           => null,
                'position'       => 'EXECUTIVE ASSISTANT I',
                'tblStructureID' => 4,
                'sg'             => 14,
                'level'          => 'S',
                'positionID'     => 11502,
                'itemNo'         => 9,
                'pageNo'         => 1,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'NOEL R. TOLOMORO',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // Public Safety and Security Management Group
            [
                'ControlNo'      => '002144',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'PUBLIC SAFETY AND SECURITY MANAGEMENT GROUP',
                'division'       => null,
                'section'        => null,
                'unit'           => null,
                'position'       => 'EXECUTIVE ASSISTANT I',
                'tblStructureID' => 4,
                'sg'             => 14,
                'level'          => 'S',
                'positionID'     => 11502,
                'itemNo'         => 83,
                'pageNo'         => 6,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'VICENTE H. DECENA',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '018382',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'PUBLIC SAFETY AND SECURITY MANAGEMENT GROUP',
                'division'       => null,
                'section'        => null,
                'unit'           => null,
                'position'       => 'EXECUTIVE ASSISTANT III',
                'tblStructureID' => 4,
                'sg'             => 20,
                'level'          => 'S',
                'positionID'     => 249,
                'itemNo'         => 79,
                'pageNo'         => 6,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'ORLANDO P. REVERA',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '018383',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'PUBLIC SAFETY AND SECURITY MANAGEMENT GROUP',
                'division'       => null,
                'section'        => null,
                'unit'           => null,
                'position'       => 'EXECUTIVE ASSISTANT II',
                'tblStructureID' => 4,
                'sg'             => 17,
                'level'          => 'S',
                'positionID'     => 910,
                'itemNo'         => 82,
                'pageNo'         => 6,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'NESTOR S. CALUBAN',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '018288',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'PUBLIC SAFETY AND SECURITY MANAGEMENT GROUP',
                'division'       => null,
                'section'        => null,
                'unit'           => null,
                'position'       => 'EXECUTIVE ASSISTANT II',
                'tblStructureID' => 4,
                'sg'             => 17,
                'level'          => 'S',
                'positionID'     => 910,
                'itemNo'         => 81,
                'pageNo'         => 6,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'JOSE B. BENGIL',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '018305',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'PUBLIC SAFETY AND SECURITY MANAGEMENT GROUP',
                'division'       => null,
                'section'        => null,
                'unit'           => null,
                'position'       => 'EXECUTIVE ASSISTANT III',
                'tblStructureID' => 4,
                'sg'             => 20,
                'level'          => 'S',
                'positionID'     => 249,
                'itemNo'         => 80,
                'pageNo'         => 6,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'FRANCISCO A. SEVILLES, JR.',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // City Mayor
            [
                'ControlNo'      => '002147',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => null,
                'division'       => null,
                'section'        => null,
                'unit'           => null,
                'position'       => 'CITY MAYOR',
                'tblStructureID' => 4,
                'sg'             => 30,
                'level'          => 'K',
                'positionID'     => 281,
                'itemNo'         => 1,
                'pageNo'         => 1,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'REY T. UY',
                'status'         => 'ELECTIVE',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // Office of the City Administrator
            [
                'ControlNo'      => '002163',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => 'OFFICE OF THE CITY ADMINISTRATOR',
                'group'          => null,
                'division'       => null,
                'section'        => null,
                'unit'           => null,
                'position'       => 'EXECUTIVE ASSISTANT IV',
                'tblStructureID' => 4,
                'sg'             => 22,
                'level'          => 'S',
                'positionID'     => 259,
                'itemNo'         => 182,
                'pageNo'         => 12,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'JOSE JOEDEL T. CAASI',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '008223',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => 'OFFICE OF THE CITY ADMINISTRATOR',
                'group'          => null,
                'division'       => null,
                'section'        => null,
                'unit'           => null,
                'position'       => 'EXECUTIVE ASSISTANT IV',
                'tblStructureID' => 4,
                'sg'             => 22,
                'level'          => 'S',
                'positionID'     => 259,
                'itemNo'         => 183,
                'pageNo'         => 12,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'VANESSA JOY T. CARIAGA',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '001613',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => 'OFFICE OF THE CITY ADMINISTRATOR',
                'group'          => null,
                'division'       => null,
                'section'        => null,
                'unit'           => null,
                'position'       => 'CITY GOVERNMENT DEPARTMENT HEAD I (CITY ADMINISTRATOR)',
                'tblStructureID' => 4,
                'sg'             => 25,
                'level'          => 'K',
                'positionID'     => 14689,
                'itemNo'         => 181,
                'pageNo'         => 12,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'EDGAR C. DE GUZMAN',
                'status'         => 'CO-TERMINOUS',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '018282',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => 'OFFICE OF THE CITY ADMINISTRATOR',
                'group'          => null,
                'division'       => 'BIDS AND AWARDS COMMITTEE SECRETARIAT & PROCUREMENT DIVISION',
                'section'        => 'ADMINISTRATIVE AND BAC SECRETARIAT SECTION',
                'unit'           => null,
                'position'       => 'ADMINISTRATIVE OFFICER V',
                'tblStructureID' => 4,
                'sg'             => 18,
                'level'          => 'A',
                'positionID'     => 14691,
                'itemNo'         => 186,
                'pageNo'         => 12,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'JOCELYN G. LAGNO',
                'status'         => 'REGULAR',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '018672',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => 'OFFICE OF THE CITY ADMINISTRATOR',
                'group'          => null,
                'division'       => 'BIDS AND AWARDS COMMITTEE SECRETARIAT & PROCUREMENT DIVISION',
                'section'        => 'PROCUREMENT SECTION',
                'unit'           => null,
                'position'       => 'ADMINISTRATIVE OFFICER I (RECORDS OFFICER I)',
                'tblStructureID' => 4,
                'sg'             => 10,
                'level'          => 'A',
                'positionID'     => 1152,
                'itemNo'         => 201,
                'pageNo'         => 13,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'RICHEL QUEEN B. GABISAN',
                'status'         => 'REGULAR',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '000186',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => 'OFFICE OF THE CITY ADMINISTRATOR',
                'group'          => null,
                'division'       => 'BIDS AND AWARDS COMMITTEE SECRETARIAT & PROCUREMENT DIVISION',
                'section'        => 'PROCUREMENT SECTION',
                'unit'           => null,
                'position'       => 'ADMINISTRATIVE ASSISTANT III (COMPUTER OPERATOR II)',
                'tblStructureID' => 4,
                'sg'             => 9,
                'level'          => 'A',
                'positionID'     => 1184,
                'itemNo'         => 205,
                'pageNo'         => 14,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'LOVEJOY S. FERNANDEZ',
                'status'         => 'REGULAR',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '001294',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => 'OFFICE OF THE CITY ADMINISTRATOR',
                'group'          => null,
                'division'       => 'BIDS AND AWARDS COMMITTEE SECRETARIAT & PROCUREMENT DIVISION',
                'section'        => 'PROCUREMENT SECTION',
                'unit'           => null,
                'position'       => 'ADMINISTRATIVE ASSISTANT III (COMPUTER OPERATOR II)',
                'tblStructureID' => 4,
                'sg'             => 9,
                'level'          => 'A',
                'positionID'     => 1184,
                'itemNo'         => 204,
                'pageNo'         => 13,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'MARLENE M. FIEL',
                'status'         => 'REGULAR',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '016677',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => 'OFFICE OF THE CITY ADMINISTRATOR',
                'group'          => null,
                'division'       => 'INTERNAL AUDIT AND MONITORING DIVISION',
                'section'        => null,
                'unit'           => null,
                'position'       => 'INTERNAL AUDITOR III',
                'tblStructureID' => 4,
                'sg'             => 18,
                'level'          => 'S',
                'positionID'     => 9395,
                'itemNo'         => 215,
                'pageNo'         => 14,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'FLORAMIE E. JUGADORA',
                'status'         => 'REGULAR',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // Special Program Management Group 2 - Community
            [
                'ControlNo'      => '007279',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'SPECIAL PROGRAM MANAGEMENT GROUP 2',
                'division'       => 'COMMUNITY AND CULTURAL AFFAIRS DEVELOPMENT DIVISION',
                'section'        => null,
                'unit'           => null,
                'position'       => 'PROJECT DEVELOPMENT OFFICER IV',
                'tblStructureID' => 4,
                'sg'             => 22,
                'level'          => 'S',
                'positionID'     => 378,
                'itemNo'         => 159,
                'pageNo'         => 11,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'ANTHONETTE J. LEONES-DELIMA',
                'status'         => 'REGULAR',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '013813',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'SPECIAL PROGRAM MANAGEMENT GROUP 2',
                'division'       => 'COMMUNITY AND CULTURAL AFFAIRS DEVELOPMENT DIVISION',
                'section'        => 'COMMUNITY AFFAIRS SECTION',
                'unit'           => null,
                'position'       => 'COMMUNITY AFFAIRS OFFICER II',
                'tblStructureID' => 4,
                'sg'             => 15,
                'level'          => 'S',
                'positionID'     => 186,
                'itemNo'         => 162,
                'pageNo'         => 11,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'JESSICA JEAN L. AMIGO-TUMBALI',
                'status'         => 'REGULAR',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'ControlNo'      => '013415',
                'office'         => 'OFFICE OF THE CITY MAYOR',
                'office2'        => null,
                'group'          => 'SPECIAL PROGRAM MANAGEMENT GROUP 2',
                'division'       => 'COMMUNITY AND CULTURAL AFFAIRS DEVELOPMENT DIVISION',
                'section'        => 'MUSLIM AND TRIBAL AFFAIRS SECTION',
                'unit'           => null,
                'position'       => 'COMMUNITY AFFAIRS OFFICER II',
                'tblStructureID' => 4,
                'sg'             => 15,
                'level'          => 'S',
                'positionID'     => 186,
                'itemNo'         => 172,
                'pageNo'         => 11,
                'position_id'    => null,
                'office_id'      => 17,
                'rank'           => 'Employee',
                'job_title'      => 'Employee',
                'name'           => 'JOMAR C. SOLAIMAN',
                'status'         => 'REGULAR',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
        ];

        DB::table('employees')->insert($employees);
    }
}
